kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "stockprices"
  # namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "15"
  numberOfInstances: 1
  enableMasterLoadBalancer: true
  volume:
    size: "1Gi"
    storageClass: "longhorn-single"

  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi